version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: